### ISSUE TITLE
Implementér en klient der viser stats for alle grupper

### ISSUE THREAD

**Issue by Minibrams** [aau-datsw/ruslan-workshop#6]
Under RUSLAN skal ruslingene kunne se en simpel oversigt der viser hvor godt hver gruppe performer. Der skal være en simpel graf for hver gruppe samt en samlet graf for hele STONKS (tænk NASDAQ oversigt). Derudover skal der, hvis det kan gøres pænt, en lille liste af de 10 seneste actions, i.e. hvilke virksomheder der blev købt og solgt af hver gruppe.

Der skal også laves klientsider til enkelte grupper. Eksempelvis: 

På `https://ruslan.dk/stonks` kan man se den store og generelle oversigt.
På `https://ruslan.dk/stonks/1` kan man se oversigten kun for gruppe 1. Dette skal umiddelbart kun bruges når ruslingene skal se om deres algoritmer virker i dev før de pusher til prod. Denne oversigt skal vise mindst det samme som den generelle, evt. mere end de 10 seneste actions.

**Comment by frederikspang** [comment]
bliver `/accounts/:id/stonks`; objekt for historik mm.
